/* =====================================================================
   PRODUKTY PO ANGIELSKU — warstwa do wyświetlania, nie klucze.

   Kluczem produktu na zawsze zostaje polska nazwa z `produkty.js` (decyzja 116):
   na niej wiszą spiżarnia, odhaczenia, wykluczenia i dopasowanie odpowiedzi AI.
   Ten plik mówi wyłącznie, co pokazać przy angielskim stole.

   Produkty bez odpowiednika poza Polską (twaróg, biała kiełbasa, zakwas na żurek)
   dostają polską nazwę z dopiskiem — ten sam zabieg co nazwy własne dań (decyzja 130).
   Człowiek w sklepie ma wiedzieć, czego szukać na półce, a nie czytać tłumaczenie,
   którego żaden sprzedawca nie zna.

   Angielszczyzna brytyjska, spójnie z datami (en-GB) i resztą interfejsu.
   ===================================================================== */

export const PRODUKTY_EN = {
  "Łosoś wędzony na zimno": "Cold-smoked salmon",
  "Łosoś świeży — filet": "Fresh salmon fillet",
  "Makrela wędzona": "Smoked mackerel",
  "Pierś z kurczaka": "Chicken breast",
  "Pierś z indyka": "Turkey breast",
  "Rostbef wołowy": "Beef sirloin",
  "Wołowina mielona 5%": "Minced beef 5%",
  "Tuńczyk z puszki": "Tinned tuna",
  "Krewetki": "Prawns",
  "Jajka": "Eggs",
  "Białko jaja": "Egg whites",
  "Twaróg półtłusty": "Twaróg (Polish curd cheese), half-fat",
  "Skyr / jogurt białkowy": "Skyr / high-protein yoghurt",
  "Jogurt grecki": "Greek yoghurt",
  "Feta": "Feta",
  "Ser żółty": "Hard cheese (Gouda-style)",
  "Mleko 2%": "Semi-skimmed milk (2%)",
  "Masło": "Butter",
  "Jarmuż": "Kale",
  "Szpinak baby": "Baby spinach",
  "Brokuły": "Broccoli",
  "Bataty": "Sweet potatoes",
  "Ziemniaki": "Potatoes",
  "Warzywa do stir-fry": "Stir-fry vegetables",
  "Papryka": "Peppers",
  "Pomidorki koktajlowe": "Cherry tomatoes",
  "Cebula": "Onions",
  "Rzodkiewki": "Radishes",
  "Ogórek": "Cucumber",
  "Awokado": "Avocados",
  "Pomarańcze": "Oranges",
  "Banany": "Bananas",
  "Jabłka": "Apples",
  "Borówki": "Blueberries",
  "Cytryny": "Lemons",
  "Czosnek": "Garlic",
  "Natka pietruszki": "Flat-leaf parsley",
  "Szczypiorek": "Chives",
  "Imbir świeży": "Fresh ginger",
  "Chleb żytni razowy": "Wholemeal rye bread",
  "Płatki owsiane": "Rolled oats",
  "Quinoa": "Quinoa",
  "Kasza gryczana": "Buckwheat groats",
  "Ryż basmati": "Basmati rice",
  "Makaron": "Pasta",
  "Ciecierzyca z puszki": "Tinned chickpeas",
  "Soczewica": "Green lentils",
  "Passata pomidorowa": "Tomato passata",
  "Daktyle bez pestek": "Pitted dates",
  "Sezam": "Sesame seeds",
  "Słonecznik łuskany": "Sunflower seeds",
  "Orzechy włoskie": "Walnuts",
  "Nerkowce": "Cashews",
  "Masło orzechowe 100%": "Peanut butter (100% peanuts)",
  "Kakao gorzkie": "Unsweetened cocoa powder",
  "Miód": "Honey",
  "Oliwa extra virgin": "Extra virgin olive oil",
  "Musztarda Dijon": "Dijon mustard",
  "Ocet jabłkowy": "Cider vinegar",
  "Sos sojowy": "Soy sauce",
  "Kurkuma": "Ground turmeric",
  "Kmin rzymski": "Ground cumin",
  "Papryka wędzona": "Smoked paprika",
  "Tymianek": "Dried thyme",
  "Kulka mocy": "Energy ball",
  "Kawa z mlekiem": "Coffee with milk",
  "Piwo": "Beer",
  "Wino wytrawne": "Dry wine",
  "Mąka pszenna": "Plain flour",
  "Pesto": "Pesto",
  "Hummus": "Hummus",
  "Curry w proszku": "Curry powder",
  "Mleko kokosowe": "Coconut milk",
  "Chili w proszku": "Chilli powder",
  "Marchew": "Carrots",
  "Oregano suszone": "Dried oregano",
  "Parmezan": "Parmesan",
  "Tortilla pszenna": "Flour tortillas",
  "Mozzarella": "Mozzarella",
  "Bazylia świeża": "Fresh basil",
  "Cukinia": "Courgettes",
  "Granola": "Granola",
  "Schab wieprzowy": "Pork loin",
  "Wieprzowina mielona": "Minced pork",
  "Kurczak — porcja rosołowa": "Chicken soup pack (back and wings)",
  "Kiełbasa wiejska": "Kiełbasa (Polish smoked sausage)",
  "Biała kiełbasa": "Biała kiełbasa (Polish white sausage)",
  "Boczek wędzony": "Smoked bacon",
  "Bułka tarta": "Breadcrumbs",
  "Śmietana 18%": "Sour cream 18%",
  "Olej rzepakowy": "Rapeseed oil",
  "Koperek": "Dill",
  "Kapusta biała": "White cabbage",
  "Kapusta kiszona": "Sauerkraut",
  "Ogórki kiszone": "Dill pickles",
  "Pietruszka korzeń": "Parsley root",
  "Seler korzeniowy": "Celeriac",
  "Por": "Leeks",
  "Śliwki suszone": "Prunes",
  "Grzyby suszone": "Dried mushrooms",
  "Zakwas na żurek": "Żurek sour starter",
  "Majeranek": "Dried marjoram",
  "Cynamon": "Ground cinnamon",
  "Fasola biała z puszki": "Tinned white beans",
  "Groszek konserwowy": "Tinned peas",
  "Majonez": "Mayonnaise",
  "Buraki": "Beetroot",
  "Tofu naturalne": "Plain tofu",
  "Tahini": "Tahini",
  "Ricotta": "Ricotta",
  "Dynia": "Pumpkin",
  "Kasza jaglana": "Millet",
  "Fasola czerwona z puszki": "Tinned kidney beans",
  "Kukurydza konserwowa": "Tinned sweetcorn",
  "Pieczarki": "Button mushrooms",
  "Makaron ramen": "Ramen noodles",
  "Makaron ryżowy": "Rice noodles",
  "Miso jasne": "White miso",
  "Nori": "Nori",
  "Olej sezamowy": "Sesame oil",
  "Gochujang": "Gochujang",
  "Panko": "Panko breadcrumbs",
  "Kiełki fasoli mung": "Bean sprouts",
  "Sos rybny": "Fish sauce",
  "Tamaryndowiec": "Tamarind paste",
  "Cukier trzcinowy": "Cane sugar",
  "Orzeszki ziemne": "Peanuts",
  "Bakłażan": "Aubergines",
  "Jagnięcina": "Lamb",
  "Dorsz — filet": "Cod fillet",
  "Estragon świeży": "Fresh tarragon",
  "Kolendra świeża": "Fresh coriander",
  "Śliwki tkemali": "Tkemali (Georgian plum sauce)",
  "Limonki": "Limes",
  "Cebula czerwona": "Red onions",
  "Papryczka chili": "Fresh chillies",
  "Soczewica czerwona": "Red lentils",
  "Pomidory z puszki": "Tinned tomatoes",
  "Garam masala": "Garam masala",
  "Masło klarowane": "Ghee",
  "Wakame": "Wakame",
  "Kalafior": "Cauliflower",
  "Ciecierzyca sucha": "Dried chickpeas",
  "Napój owsiany": "Oat drink",
  "Mąka z ciecierzycy": "Gram flour",
  "Siemię lniane": "Flaxseed",
  "Syrop klonowy": "Maple syrup",
};

/* Działy sklepu. „Dopisane” i „Inne” nie są tutaj — powstają w kodzie zakupów,
   nie w danych, i tłumaczy je słownik interfejsu. */
export const DZIALY_EN = {
  "Mięso i ryby": "Meat and fish",
  "Nabiał": "Dairy and chilled",
  "Warzywa i owoce": "Fruit and vegetables",
  "Spiżarnia": "Store cupboard",
  "Szafka": "Oils, spices and sauces",
  "—": "—",
};
