/* =====================================================================
   TŁUMACZENIA — słownik polski → angielski.

   KLUCZEM JEST POLSKI NAPIS (decyzja 120). W kodzie stoi t("Zapisz"),
   a nie t("przyciski.zapisz"), z jednego powodu: Miłosz czyta ten kod
   i ma widzieć, co jest na ekranie, zamiast odszyfrowywać nazwy szufladek.
   Cena tego wyboru jest znana i przyjęta — zmiana polskiego napisu zrywa
   powiązanie ze słownikiem. Dlatego zrywa je GŁOŚNO: test-tlumaczenia.mjs
   oblewa na każdym t(), które nie ma pozycji w słowniku, i nie da się
   wtedy wydać wersji.

   Brak tłumaczenia zwraca polski napis, nie pustkę i nie wyjątek. Ekran
   z jednym polskim słowem jest zły, ale ekran z dziurą albo białą stroną
   jest gorszy — a wyłapuje to test, nie użytkownik.

   NAZW WŁASNYCH NIE TŁUMACZYMY (decyzja 118): tortilla zostaje tortillą,
   chili chili, curry curry. Wchodzą do słownika tylko wtedy, gdy stoją
   w dłuższym zdaniu, które trzeba przetłumaczyć w całości.

   DWA WEJŚCIA, JEDEN SŁOWNIK:
   - w ekranach (Alpine) wołamy t("…") z powłoki — czyta this.jezyk, więc
     przełączenie języka od razu przerysowuje ekran;
   - w modułach bez Alpine (pomoc.js, kuchnia.js) wołamy tb("…"), które
     bierze język ustawiony przez powłokę przez ustawJezykModulow().
   ===================================================================== */

export const SLOWNIK = {
  /* Nagłówki ekranów — podawane do danePowloki(), nie przez t(). */
  "Jadłospis": "Meal plan",
  "Ułóż sam albo daj apce ułożyć z tego, co lubicie.": "Build it yourself or let the app build it from what you like.",
  "Przepisy": "Recipes",
  "Wszystko, co polubiliście — z krokami i gramaturą.": "Everything you liked — with steps and amounts.",
  "Wykluczenia": "Exclusions",
  "Zanim pokażę dania — czy jest coś, czego w ogóle nie jecie?": "Before I show you any dishes — is there anything you don't eat at all?",
  "Jak wygląda Wasz zwykły okres i czym gotujecie.": "What your usual period looks like and what you cook with.",
  "Lista zakupów": "Shopping list",
  "Policzona z jadłospisu. Działa też bez zasięgu.": "Counted from the plan. Works without a signal too.",
  "Dania": "Dishes",

  /* Komunikaty ekranów — mrugnij() i linia dla czytnika ekranu (sesja A, część druga).
     Fragmenty z wiodącą albo końcową spacją są celowe: napis powstaje ze sklejenia
     z liczbą albo imieniem, więc spacja należy do tłumaczenia, nie do kodu. */
  "Dotknij, żeby wybrać zdjęcia": "Tap to choose photos",
  "Trwa dłużej niż zwykle, ale jeszcze liczy.": "Taking longer than usual, but still working.",
  "Nie udało się połączyć — sprawdź internet i spróbuj ponownie.": "Connection failed — check your connection and try again.",
  "Nie udało się sprawdzić — sprawdź internet.": "Checking failed — check your connection.",
  "Wpisz imię albo pseudonim.": "Type a name or a nickname.",
  "Za długie — maksymalnie 30 znaków.": "Too long — 30 characters at most.",
  "Ktoś taki już siedzi przy stole.": "Someone by that name is already at the table.",
  "Nie udało się dodać — sprawdź internet.": "Adding failed — check your connection.",
  "Zasłużyłeś. Miłego!": "You have earned it. Enjoy!",
  "Zero marnowania. Szacun.": "Zero waste. Respect.",
  "No dobra, każdy ma taki dzień.": "Fair enough, everyone has days like that.",
  "Zbieram…": "Collecting…",
  "Nie dodaliście jeszcze żadnego własnego dania.": "You have not added a dish of your own yet.",
  "Nie udało się pobrać — sprawdź internet i spróbuj ponownie.": "Download failed — check your connection and try again.",
  "Odhaczone zapisane na tym telefonie — zsynchronizuje się, gdy wróci internet.": "Ticks saved on this phone — they will sync when the connection is back.",
  "Pokazuję ostatnią zapisaną listę — sprawdzam, czy jest nowsza…": "Showing the last saved list — checking for a newer one…",
  " dań. Wystarczy, żeby ułożyć jadłospis.": " dishes. Enough to build a plan.",
  " kcal — bez ": " kcal — without ",
  " kcal.": " kcal.",
  " — ale ta przeglądarka tego nie zapamięta.": " — but this browser will not remember it.",
  ", tego nie ma w słowniku.": ", those are not in the product list.",
  "Baza nie pozwala zapisać spiżarni — to reguły dostępu, nie internet.": "The database will not save the pantry — that is access rules, not your connection.",
  "Brak połączenia z bazą.": "No connection to the database.",
  "Cały okres zaplanowany. Nic tu po mnie.": "The whole period is planned. Nothing left for me to do.",
  "Cofnięto": "Undone",
  "Coś nie zadziałało przy wczytywaniu.": "Something went wrong while loading.",
  "Danie dodane": "Dish added",
  "Dwadzieścia pięć dań. Miesiąc bez powtórek.": "Twenty-five dishes. A month without repeats.",
  "Gotowe — Forkast jest na ekranie.": "Done — Forkast is on your home screen.",
  "Jadłospis otwarty. Możesz układać plan albo przeglądać dalej.": "The meal plan is open. Build it now or keep swiping.",
  "Jadłospis wyczyszczony": "Meal plan cleared",
  "Jeden składnik. Szanujemy minimalizm.": "One ingredient. We respect minimalism.",
  "Kod skopiowany": "Code copied",
  "Może po prostu gotujecie inaczej. Dodaj swoje dania.": "Maybe you simply cook differently. Add your own dishes.",
  "Najpierw dodaj kogoś do stołu": "Add someone to the table first",
  "Najpierw powiedz w Ustawieniach, kim jesteś przy tym stole.": "First tell Settings who you are at this table.",
  "Nie udało się skopiować — zaznacz kod i skopiuj ręcznie.": "Copying failed — select the code and copy it by hand.",
  "Nie udało się usunąć — sprawdź internet i spróbuj ponownie.": "Deleting failed — check your connection and try again.",
  "Nie udało się usunąć — sprawdź internet.": "Deleting failed — check your connection.",
  "Nie udało się wylosować wolnego kodu — spróbuj jeszcze raz.": "Could not draw a free code — try once more.",
  "Nie udało się zapisać — sprawdź internet i spróbuj ponownie.": "Saving failed — check your connection and try again.",
  "Nie udało się zapisać: ": "Saving failed: ",
  "Nie udało się założyć stołu — sprawdź internet.": "Setting the table failed — check your connection.",
  "Nikt nie wybrany — licznik schowany.": "Nobody selected — the counter stays hidden.",
  "O tej porze to już nawet nie kolacja.": "At this hour that is not even dinner any more.",
  "Od początku. Przesuwaj tak, jak myślisz dziś.": "From the top. Swipe the way you feel today.",
  "Odhaczone. ": "Ticked off. ",
  "Pierwsze danie na liście. Już się da z tego coś ułożyć.": "First dish on the list. That is already something to build on.",
  "Plan gotowy. Lista zakupów policzy się sama.": "Plan ready. The shopping list counts itself.",
  "Polubiliście ": "You liked ",
  "Połowa za Wami.": "Halfway through.",
  "Ta przeglądarka tego nie zapamięta — licznik zniknie po zamknięciu.": "This browser will not remember it — the counter goes when you close it.",
  "Ten posiłek nie jest zaplanowany dla Ciebie.": "This meal is not planned for you.",
  "Ten telefon to ": "This phone is ",
  "Trzeci raz na mieście. Restauracje Cię lubią.": "Third time eating out. The restaurants like you.",
  "Ty": "you",
  "Wszystko w koszyku. Możesz iść do domu.": "Everything is in the basket. You can go home.",
  "Wszystko w koszyku. yeah yeah 🎵": "Everything is in the basket. yeah yeah 🎵",
  "Wybredny dziś jesteś.": "Picky today, are we.",
  "Wyłączyliście wszystko. Post czy pomyłka?": "You switched everything off. Fasting, or a slip?",
  /* Pasek nawigacji — etykiety z ZAKLADKI w powloka.js, podawane przez t(z.nazwa).
     Pięć z sześciu miało tłumaczenia z innych miejsc, brakowało tylko „Zakupy”. */
  "Zakupy": "Shopping",
  " — otworzy się po ": " — opens after ",
  " daniach": " dishes",
  "Przesuwaj: to, co polubicie, trafi do jadłospisu.": "Swipe: what you like goes into the plan.",
  "Strona z książki, kartka z zeszytu, zrzut ekranu — albo sam talerz z jedzeniem.": "A page from a book, a sheet from a notebook, a screenshot — or just the plate of food.",
  "Najlepiej 1–2 zdjęcia. Przy większej liczbie AI może nie zdążyć.": "One or two photos work best. With more, the AI may run out of time.",
  "Wyślij do AI": "Send to AI",
  "Wolisz wpisać ręcznie?": "Rather type it in yourself?",
  "Sprawdź, zanim zapiszę": "Check it before I save",
  "Nie ma tu ani jednego dania, które da się zapisać.": "There is not a single dish here that can be saved.",
  "Dodaj do moich dań": "Add to my dishes",
  "Odrzuć": "Discard",
  "Zapisane": "Saved",
  "Dopisz do listy": "Add to the list",
  /* Tytuły kart przeglądarki — nie da się ich owinąć w t() w szablonie,
     bo <head> jest poza Alpine. Tłumaczy je powłoka (patrz powloka.js). */
  "Dania — Forkast": "Dishes — Forkast",
  "Jadłospis — Forkast": "Meal plan — Forkast",
  "Zakupy — Forkast": "Shopping — Forkast",
  "Przepisy — Forkast": "Recipes — Forkast",
  "Dodaj przez AI — Forkast": "Add with AI — Forkast",
  "Dodaj danie — Forkast": "Add a dish — Forkast",
  "Ustawienia — Forkast": "Settings — Forkast",
  " os. · ": " ppl · ",
  " składników": " ingredients",
  " · na ": " · for ",
  "(można wybrać kilka)": "(you can pick several)",
  "AI poprawia liczby… ": "AI is fixing the numbers… ",
  "AI układa wersję restauracyjną… ": "AI is writing the restaurant version… ",
  "Albo dodaj własny przepis": "Or add your own recipe",
  "Bez AI — po prostu to, co i tak gotujecie.": "No AI — just what you cook anyway.",
  "Bez gotowania": "No cooking",
  "Bez limitu jest sensowne, jeśli gotujecie większą porcję na kilka dni — albo jeśli polubionych dań jest na razie mało.": "No limit makes sense if you cook a bigger batch for several days — or if you have only a few liked dishes so far.",
  "Co masz w kuchni": "What you have in the kitchen",
  "Cofnij ostatnią": "Undo the last one",
  "Coś nie działa? Napisz do mnie": "Something not working? Write to me",
  "Cześć, tu Forkast": "Hi, this is Forkast",
  "Czy dania mogą się powtarzać": "Can dishes repeat",
  "Czym gotujecie": "What you cook with",
  "Dalej — wybierz dania": "Next — pick dishes",
  "Dania, które sami dodaliście. Możesz je pobrać jako plik i trzymać u siebie, niezależnie od tej aplikacji.": "Dishes you added yourselves. You can download them as a file and keep them on your own, independently of this app.",
  "Danie trafiło do Waszych dań jako polubione.": "The dish was added to your dishes as liked.",
  "Dlaczego warto przejrzeć więcej dań": "Why it pays to review more dishes",
  "Do kupienia": "To buy",
  "Dodaj": "Add",
  "Dodaj danie": "Add a dish",
  "Dodaj do ekranu": "Add to home screen",
  "Dodaj do spiżarni": "Add to the pantry",
  "Dodaj kolejne": "Add another",
  "Dodaj przez AI": "Add with AI",
  "Dodaj przynajmniej jedną osobę, żeby ruszyć dalej.": "Add at least one person to go on.",
  "Dodaj składnik": "Add an ingredient",
  "Dodane!": "Added!",
  "Domyślnie apka idzie za ustawieniem telefonu.": "By default the app follows your phone's setting.",
  "Dopisz": "Add",
  "Dopisz coś do listy — np. pasta do zębów": "Add something to the list — e.g. toothpaste",
  "Dopisz pozycję do listy zakupów": "Add an item to the shopping list",
  "Dosiadam się — mam kod": "Joining in — I have a code",
  "Dotknij imienia, żeby je poprawić. Zmiana widoczna dla całego stołu — plan, zakupy i odhaczenia zostają przy tej samej osobie.": "Tap a name to change it. The change is visible to the whole table — the plan, the shopping and the ticks stay with the same person.",
  "Dotyczy całego stołu — wszyscy przy nim zobaczą tę zmianę.": "Applies to the whole table — everyone at it will see this change.",
  "Dołącz": "Join",
  "Długość okresu": "Length of the period",
  "Ekran gaśnie. Dotknij, żeby świecił.": "The screen dims. Tap to keep it on.",
  "Ekran nie gaśnie. Dotknij, żeby wyłączyć.": "The screen stays on. Tap to turn it off.",
  "Forkast zapisuje tylko to, co sam wpiszesz: imiona albo pseudonimy osób przy stole, czego nie jecie i jakie dania lubicie. Dane leżą w bazie Google (Firebase) i możesz je skasować jednym przyciskiem w każdej chwili.": "Forkast saves only what you type in: the names or nicknames of the people at the table, what you don't eat and which dishes you like. The data sits in a Google database (Firebase) and you can wipe it with one button at any time.",
  "Gaśnie": "Dims",
  "Ile — sztuk, gramów, opakowań": "How much — pieces, grams, packs",
  "Imiona przy stole": "Names at the table",
  "Imię lub pseudonim": "Name or nickname",
  "Jak to działa": "How it works",
  "Jak to zrobić": "How to make it",
  "Jak to zrobić — wersja restauracyjna": "How to make it — restaurant version",
  "Jasne": "Got it",
  "Jeśli coś wygląda inaczej niż u innych, dotknij „Pobierz najnowszą”.": "If something looks different than for the others, tap „Get the latest”.",
  "Jeśli musisz mrużyć oczy — zwiększ. Dotyczy tylko tego urządzenia.": "If you have to squint — make it bigger. This device only.",
  "Język": "Language",
  "Kim jesteś przy tym stole": "Who you are at this table",
  "Kod Waszego stołu": "Your table code",
  "Kod stołu": "Table code",
  "Kod stołu, osoby przy stole": "Table code, people at the table",
  "Kod tego stołu": "This table's code",
  "Kopiuj": "Copy",
  "Kto siada do stołu? Dodaj przynajmniej siebie — resztę możesz dopisać kiedy chcesz.": "Who sits down at the table? Add at least yourself — you can add the rest whenever you like.",
  "Które posiłki i dla kogo": "Which meals and for whom",
  "Który z Was to Ty?": "Which one of you is you?",
  "Language / Język": "Language",
  "Limit powtórzeń": "Repeat limit",
  "Lubię": "I like it",
  "Na ile dni planujecie naraz": "How many days you plan at once",
  "Na ile osób jest ta gramatura": "How many people these amounts are for",
  "Na pewno? Dotknij ponownie — tego nie da się cofnąć": "Sure? Tap again — this cannot be undone",
  "Najpierw dodaj kogoś do stołu na ekranie startowym.": "First add someone to the table on the start screen.",
  "Nakrywam nowy stół": "Setting a new table",
  "Nawigacja główna": "Main navigation",
  "Nazwa dania": "Dish name",
  "Nazwa dania, zdjęcie przepisu — albo zdjęcie samego talerza.": "A dish name, a photo of a recipe — or a photo of the plate itself.",
  "Nic do kupienia. Ułóż jadłospis, a lista policzy się sama — albo dopisz coś ręcznie na dole.": "Nothing to buy. Build a plan and the list counts itself — or add something by hand below.",
  "Nic nie trafiło?": "Nothing landed?",
  "Nic takiego nie masz.": "You have nothing like that.",
  "Nic z tego? Dodajcie swoje dania.": "None of these? Add your own dishes.",
  "Nie lubię": "Not for me",
  "Nie masz jeszcze polubionych dań. Przejrzyj Dania — przepisy pojawią się tutaj same.": "You have no liked dishes yet. Go through Dishes — the recipes will show up here by themselves.",
  "Nie masz polubionego dania, które pasuje na ten posiłek.": "You have no liked dish that fits this meal.",
  "Nie teraz": "Not now",
  "Nie wygaszaj ekranu": "Keep the screen on",
  "Nie wygaszaj ekranu, gdy używam aplikacji": "Keep the screen on while I'm using the app",
  "Nikt nie wybrany — licznik w jadłospisie jest wtedy schowany.": "Nobody chosen — the counter in the plan stays hidden then.",
  "Owsianka, koktajl czy kanapka nie należą do żadnej kuchni narodowej — zostaw „uniwersalna”.": "Porridge, a smoothie or a sandwich belong to no national cuisine — leave „universal”.",
  "Piekarnik": "Oven",
  "Po co spiżarnia": "What the pantry is for",
  "Pobieram…": "Fetching…",
  "Pobierz najnowszą": "Get the latest",
  "Pobierz nasze dania": "Download our dishes",
  "Podaj go tym, którzy siadają z Wami do stołu. Wpisują go przy pierwszym wejściu.": "Give it to the people who sit down with you. They type it in the first time they come in.",
  "Podaj go tym, którzy siadają z Wami do stołu. Zapisz, zanim zamkniesz kartę.": "Give it to the people who sit down with you. Write it down before you close the tab.",
  "Podstawowa": "Basic",
  "Pokaż dania": "Show dishes",
  "Produkt": "Product",
  "Przejdź do aplikacji": "Go to the app",
  "Przejdź do dań": "Go to dishes",
  "Przejdź do jadłospisu": "Go to the plan",
  "Przejrzeliście wszystkie dania, więc karta Dań zeszła z paska. Wróci, gdy dojdą nowe.": "You have been through every dish, so the Dishes tab left the bar. It comes back when new ones arrive.",
  "Przejrzyj dania jeszcze raz": "Go through the dishes again",
  "Przejrzyj jeszcze raz": "Go through them again",
  "Przepis mówiący „smaż na 6/9” to instrukcja do indukcji — na gazie nie znaczy nic. Powiedz, co masz, a nowe dania od AI będą pod to pisane.": "A recipe saying „fry at 6/9” is an instruction for induction — on gas it means nothing. Tell us what you have and new AI dishes will be written for it.",
  "Przez AI": "With AI",
  "Przełącz tryb ciemny": "Toggle dark mode",
  "Przydaje się przy wózku w sklepie i przy mokrych rękach w kuchni. W tle gaśnie normalnie i nie zjada baterii.": "Handy with a trolley in the shop and wet hands in the kitchen. In the background it dims normally and does not eat the battery.",
  "Płyta": "Hob",
  "Restauracyjna": "Restaurant",
  "Rodzaj piekarnika": "Type of oven",
  "Rodzaj płyty": "Type of hob",
  "Rozmiar liter": "Text size",
  "Ręcznie": "By hand",
  "Schowaj ustawienia stołu": "Hide table settings",
  "Składniki": "Ingredients",
  "Spiżarnia jest pusta. To w porządku — wpiszcie tylko to, czego macie więcej niż na jeden raz.": "The pantry is empty. That is fine — write in only what you have more of than one go.",
  "Sposób dodania": "How to add it",
  "Sprawdzam…": "Checking…",
  "Sprzęt kuchenny": "Kitchen equipment",
  "Spróbuj jeszcze raz": "Try again",
  "Szukaj dania": "Search dishes",
  "Szukaj dania…": "Search dishes…",
  "Ta przeglądarka tego nie potrafi. Jeśli otwierasz Forkast z linku w WhatsAppie albo Messengerze, otwórz go w Safari albo Chrome — tam zadziała.": "This browser cannot do it. If you are opening Forkast from a link in WhatsApp or Messenger, open it in Safari or Chrome — it works there.",
  "Ten posiłek jest zaplanowany w wersji restauracyjnej — lista zakupów liczy z tego składu.": "This meal is planned in the restaurant version — the shopping list counts from those ingredients.",
  "To danie nie ma zapisanych kroków — dodaj je przez AI, jeśli chcesz mieć przepis.": "This dish has no saved steps — add it with AI if you want a recipe.",
  "To nie mój stół — zacznij od nowa": "Not my table — start over",
  "To wartość domyślna dla nowego okresu, nie reguła na sztywno — w jadłospisie da się zmienić pojedynczy posiłek w pojedynczym dniu.": "This is the default for a new period, not a fixed rule — in the plan you can change a single meal on a single day.",
  "To wszystko na teraz": "That is all for now",
  "Tryb ciemny": "Dark mode",
  "Tryb jasny": "Light mode",
  "Tydzień to tylko najczęstszy wybór, nie jedyny — jeśli robicie zakupy co trzy dni albo raz na dwa tygodnie, ustaw to tutaj.": "A week is only the most common choice, not the only one — if you shop every three days or once a fortnight, set it here.",
  "Tylko na tym telefonie. Plan i lista zakupów są wspólne — to potrzebne po to, żeby kalorie liczyły się Tobie, a nie całemu stołowi.": "This phone only. The plan and the shopping list are shared — this is here so the calories count for you, not for the whole table.",
  "Tylko na tym telefonie. Potrzebne, żeby ptaszek przy posiłku liczył kalorie Tobie, a nie całemu domowi.": "This phone only. Needed so the tick on a meal counts the calories for you, not for the whole household.",
  "Typ posiłku": "Meal type",
  "Ustawienia": "Settings",
  "Usuń składnik ": "Remove ingredient ",
  "Usuń ten stół i wszystko, co przy nim zapisaliśmy": "Delete this table and everything saved at it",
  "Ułóż automatycznie": "Fill it in for us",
  "Ułóż jadłospis": "Build the plan",
  "W koszyku": "In the basket",
  "W porządku — te dania miały wystarczyć na start, nie być kompletne. Dodaj swoje.": "That is fine — these dishes were meant to be a start, not a complete set. Add your own.",
  "Wasz sprzęt": "Your equipment",
  "Wasz stół jest nakryty. Wchodzisz i planujecie dalej.": "Your table is set. Come in and carry on planning.",
  "Wasze dania": "Your dishes",
  "Wersja aplikacji:": "App version:",
  "Wersja przepisu": "Recipe version",
  "Wersja restauracyjna — AI, ok. 10 s": "Restaurant version — AI, about 10 s",
  "Witaj z powrotem": "Welcome back",
  "Wolisz, żeby AI to wypełniło?": "Rather have AI fill this in?",
  "Wpisz ręcznie": "Type it in yourself",
  "Wpiszcie, ile czego macie w domu. Lista wyżej odejmie to od zakupów, żeby nie kazała Wam kupować kilograma mąki co tydzień.": "Write in how much of what you have at home. The list above subtracts it from the shopping, so it does not tell you to buy a kilo of flour every week.",
  "Wróć": "Back",
  "Wróć do dań": "Back to dishes",
  "Wszystkie posiłki wyłączone tego dnia.": "Every meal is off that day.",
  "Wyczyść": "Clear",
  "Względem podstawowej:": "Against the basic version:",
  "Z jakiej kuchni": "Which cuisine",
  "Zakładam…": "Setting it up…",
  "Zamieniamy najgorsze pytanie dnia — „co ja dziś zjem?” — w coś, co da się przeżyć. Zaczynamy?": "We turn the worst question of the day — „what do I eat today?” — into something you can live with. Shall we?",
  "Zamknij": "Close",
  "Zapasy w spiżarni domowej": "What is in the pantry at home",
  "Zapisuję…": "Saving…",
  "Zapisz danie": "Save the dish",
  "Zmień danie": "Change the dish",
  "Zobacz listę zakupów": "See the shopping list",
  "bez piekarnika nie zrobisz": "cannot be made without an oven",
  "dziś": "today",
  "gramy": "grams",
  "ile": "how much",
  "min": "min",
  "nie wchodzi do listy zakupów": "not counted into the shopping list",
  "np. NH7XOO": "e.g. NH7XOO",
  "np. Naleśniki z dżemem": "e.g. Pancakes with jam",
  "restauracyjna": "restaurant",
  "wymaga piekarnika": "needs an oven",
  "zacznij dzień wcześniej": "start a day earlier",
  "Świeci": "Stays on",
  "— dotknij, żeby wybrać —": "— tap to choose —",
  "— wyłączone, dotknij, żeby włączyć —": "— off, tap to turn on —",
  "✓ gotowe": "✓ done",

  /* Sesja A, część trzecia (11 września): moduły, wstawki i napisy schowane w wyrażeniach. */
  "Zaznacz {ile} dań, które lubicie jeść — z nich apka ułoży jadłospis i policzy zakupy. Nie musisz przeglądać wszystkich, wystarczy pierwsze, które pasują.": "Pick {ile} dishes you like to eat — the app builds the meal plan and the shopping list from them. No need to go through them all; the first ones that fit are enough.",
  "Jeszcze jedno danie i otworzy się jadłospis.": "One more dish and the meal plan opens.",
  "Jeszcze {ile} dania i otworzy się jadłospis.": "{ile} more dishes and the meal plan opens.",
  "Zaznacz dania, które lubicie jeść": "Pick dishes you like to eat",
  "Jeszcze jedno i otworzy się jadłospis": "One more and the meal plan opens",
  "Jeszcze {ile} do otwarcia jadłospisu": "{ile} more to open the meal plan",
  "Przejrzano {ile} z {z} dań": "{ile} of {z} dishes reviewed",
  "kuchnia {nazwa}": "{nazwa} cuisine",
  "na {ile} os.": "serves {ile}",
  "{ile} składników": "{ile} ingredients",
  "Coś nie zadziałało: {powod}": "Something went wrong: {powod}",
  "Brak internetu — część rzeczy może nie działać.": "No connection — some things may not work.",
  "Polubione": "Liked",
  "Pominięte": "Skipped",
  "Coś nie zadziałało. Spróbuj odświeżyć.": "Something went wrong. Try refreshing.",
  "Coś nie zadziałało przy wczytywaniu: {powod}": "Something went wrong while loading: {powod}",
  "Cześć, {imie}": "Hi, {imie}",
  "Imię: {imie}. Zmień, jeśli chcesz.": "Name: {imie}. Change it if you like.",
  "Usuń {imie} ze stołu": "Remove {imie} from the table",
  "Twój kod ma w środku „{slowo}”. Dobry znak.": "Your code has “{slowo}” in it. Good sign.",
  "Nie dochodzą zmiany osób przy stole: {powod}": "Changes to the people at the table are not coming through: {powod}",
  "Za dużo prób — odczekaj {ile} s.": "Too many attempts — wait {ile} s.",
  " (kolejna próba za {ile} s)": " (next attempt in {ile} s)",
  "To nie wygląda na poprawny kod — sprawdź, czy nie brakuje znaku.": "That does not look like a valid code — check that no character is missing.",
  "Nie ma stołu z takim kodem. Sprawdź u osoby, która go wysłała.": "There is no table with that code. Check with the person who sent it.",
  "{imie} dołącza do stołu": "{imie} joins the table",
  "Nie da się zapisać tego imienia.": "That name cannot be saved.",
  "{stare} to teraz {imie}": "{stare} is now {imie}",
  "Zapisane: {imie}": "Saved: {imie}",
  "Nie udało się zmienić imienia: {powod}": "Could not change the name: {powod}",
  "Włącz {posilek}, {dzien}": "Turn on {posilek}, {dzien}",
  "{posilek}, {dzien}: {co}. Dotknij, żeby zmienić.": "{posilek}, {dzien}: {co}. Tap to change.",
  "Odznacz {posilek}, {dzien} — cofnie kalorie i odda zapas do spiżarni": "Untick {posilek}, {dzien} — removes the calories and returns the stock to the pantry",
  "Odhacz {posilek}, {dzien} jako zjedzone przez Ciebie": "Tick {posilek}, {dzien} as eaten by you",
  "Wyłącz {posilek}, {dzien}": "Turn off {posilek}, {dzien}",
  "Zdejmij danie z {posilek}, {dzien}": "Remove the dish from {posilek}, {dzien}",
  "Składniki na {ile} osobę": "Ingredients for {ile} person",
  "Składniki na {ile} osoby": "Ingredients for {ile} people",
  "Przeliczone z przepisu na {ile} os.": "Scaled from a recipe for {ile}",
  "Baza nie pozwala czytać jadłospisu — to reguły dostępu, nie internet.": "The database will not let us read the meal plan — that is access rules, not the connection.",
  "Nie dochodzą zmiany jadłospisu: {powod}": "Meal plan changes are not coming through: {powod}",
  "odhaczonych posiłków": "ticked meals",
  "spiżarni": "the pantry",
  "Baza nie pozwala czytać {co} — to reguły dostępu, nie internet.": "The database will not let us read {co} — that is access rules, not the connection.",
  "Nie dochodzą zmiany {co}: {powod}": "Changes to {co} are not coming through: {powod}",
  "Nie udało się zapisać: {powod}": "Could not save: {powod}",
  "Jednego dnia zabrakło dania na {posilek}.": "On one day there was no dish for {posilek}.",
  "W {ile} dniach nie ma czego wstawić na {posilek} — polub więcej takich dań albo wyłącz ten posiłek w Ustawieniach.": "On {ile} days there is nothing to put in for {posilek} — like more of these dishes or turn this meal off in Settings.",
  "Plan zapisany przy stole był niekompletny i nie dało się go wczytać. Ułóż go proszę na nowo — to zajmie chwilę i nic więcej nie zginęło.": "The plan saved at this table was incomplete and could not be loaded. Please build it again — it takes a moment and nothing else was lost.",
  "Nie udało się zapisać wersji: {powod}": "Could not save the version: {powod}",
  "Zdjęto danie z {posilek}": "Dish removed from {posilek}",
  "Wyłączono {posilek} — dotknij wiersza, żeby wrócić": "{posilek} turned off — tap the row to bring it back",
  "Włączono {posilek}": "{posilek} turned on",
  "(usunięte danie)": "(deleted dish)",
  "nie wybrano dania": "no dish chosen",
  "śniadanie": "breakfast",
  "lunch": "lunch",
  "obiad": "dinner",
  "przekąska": "snack",
  "kolacja": "supper",
  "na mieście": "eating out",
  "co się nawinie": "whatever's around",
  "coś z paczki": "something ready-made",
  "Ktoś przy stole ma nowszą wersję aplikacji. Odśwież stronę, żeby nie nadpisać jego zmian.": "Someone at the table has a newer version of the app. Refresh the page so you do not overwrite their changes.",
  "{ile} w koszyku": "{ile} in the basket",
  "{ile} już macie w domu": "{ile} already at home",
  "zostało {ile}": "{ile} left",
  "{produkt}, dopisane ręcznie. {stan}.": "{produkt}, added by hand. {stan}.",
  "{produkt}. Macie w domu {ile}, nie trzeba kupować.": "{produkt}. You have {ile} at home, no need to buy.",
  "{produkt}, do kupienia {ile}, w domu {wDomu}. {stan}.": "{produkt}, to buy {ile}, at home {wDomu}. {stan}.",
  "{produkt}, do kupienia {ile}. {stan}.": "{produkt}, to buy {ile}. {stan}.",
  "mamy": "got it",
  "{ile} w domu": "{ile} at home",
  "{ile} jest w domu": "{ile} at home",
  "Usuń {produkt} z listy": "Remove {produkt} from the list",
  "Ile gramów: {produkt}": "How many grams: {produkt}",
  "Usuń {produkt} ze spiżarni": "Remove {produkt} from the pantry",
  "{ile} z {z} w koszyku": "{ile} of {z} in the basket",
  "Dopisane, treść nasłuchu: {powod}": "Added items, listener body: {powod}",
  "dopisanych pozycji": "added items",
  "Dopisane padły na kroku „{etap}”: {powod}": "Added items failed at step “{etap}”: {powod}",
  "odhaczeń": "ticks",
  "Brak połączenia — to ostatnia lista zapisana na tym telefonie.": "No connection — this is the last list saved on this phone.",
  "Brak połączenia i nie mam zapisanej listy. Wejdź tu raz z internetem.": "No connection and no saved list. Open this screen once with a connection.",
  "Lista działa, ale zmiany drugiej osoby mogą nie dochodzić: {powod}": "The list works, but the other person's changes may not come through: {powod}",
  "jadłospisu": "the meal plan",
  "wersji restauracyjnych": "restaurant versions",
  "Brak połączenia — dopiszę, gdy wróci internet.": "No connection — I will add it when the connection is back.",
  "Dopisano „{tekst}”": "Added “{tekst}”",
  "Nie udało się dopisać: {powod}": "Could not add: {powod}",
  "z powrotem na liście": "back on the list",
  "w koszyku": "in the basket",
  "Skreślono „{produkt}”": "Crossed off “{produkt}”",
  "Nie udało się skreślić: {powod}": "Could not cross off: {powod}",
  "Dopisane": "Added",
  "dopisane ręcznie": "added by hand",
  "Został tylko {produkt}. Dasz radę.": "Only {produkt} left. You've got this.",
  "nie ma tego w tym okresie": "not used in this period",
  "nie starczy na cały okres": "not enough for the whole period",
  "starczy na ten okres": "enough for this period",
  "starczy na {ile} okresy": "enough for {ile} periods",
  "nic jeszcze nie odhaczone": "nothing ticked yet",
  "{kcal} kcal · B {b} · W {w} · T {tl}": "{kcal} kcal · P {b} · C {w} · F {tl}",
  "do 20 min": "up to 20 min",
  "do 45 min": "up to 45 min",
  "ponad 45 min": "over 45 min",
  "płyta elektryczna nagrzewa się wolniej": "an electric hob heats up more slowly",
  "piekarnik bez termoobiegu grzeje dłużej": "an oven without a fan takes longer",
  "bez blendera trzeba przetrzeć przez sitko": "without a blender it has to go through a sieve",
  "bez woka trzeba smażyć partiami": "without a wok it has to be fried in batches",
  "Dłużej, bo: {powody}.": "Longer, because: {powody}.",
  "Indukcja": "Induction",
  "moc w stopniach, szybko reaguje": "power in levels, reacts fast",
  "Gaz": "Gas",
  "płomień, natychmiastowa zmiana": "flame, instant change",
  "Płyta elektryczna": "Electric hob",
  "wolno się nagrzewa i stygnie": "slow to heat up and cool down",
  "Z termoobiegiem": "With a fan",
  "Góra-dół": "Top and bottom heat",
  "Nie mam piekarnika": "I have no oven",
  "Patelnia": "Frying pan",
  "Patelnia żeliwna": "Cast-iron pan",
  "Duży garnek": "Large pot",
  "Garnek żeliwny / brytfanna": "Cast-iron pot / roasting tin",
  "Wok": "Wok",
  "Blender": "Blender",
  "Mikser": "Hand mixer",
  "polska": "Polish",
  "włoska": "Italian",
  "japońska": "Japanese",
  "koreańska": "Korean",
  "chińska": "Chinese",
  "tajska": "Thai",
  "indyjska": "Indian",
  "meksykańska": "Mexican",
  "hiszpańska": "Spanish",
  "grecka": "Greek",
  "francuska": "French",
  "gruzińska": "Georgian",
  "peruwiańska": "Peruvian",
  "bliskowschodnia": "Middle Eastern",
  "uniwersalna": "universal",
  "Mięso": "Meat",
  "Ryby i owoce morza": "Fish and seafood",
  "Nabiał": "Dairy",
  "Jajka": "Eggs",
  "Gluten": "Gluten",
  "Orzechy": "Nuts",
  "Normalny": "Normal",
  "Duży": "Large",
  "Bardzo duży": "Very large",
  "Ekran nie zgaśnie, dopóki tu jesteś.": "The screen will stay on while you are here.",
  "Ekran gaśnie normalnie.": "The screen dims as usual.",
  "Inne": "Other",
  "bez limitu": "no limit",
  "raz": "once",
  "do 2×": "up to 2×",
  "do 3×": "up to 3×",
  "{ile} dni": "{ile} days",
  "Imię: {imie}. Dotknij, żeby poprawić.": "Name: {imie}. Tap to correct it.",
  "Posiłek {posilek}": "Meal: {posilek}",
  "Pobrano {ile} dań.": "Downloaded {ile} dishes.",
  "Składniki na {ile} porcje": "Ingredients for {ile} servings",
  "Nie mogę czytać wersji restauracyjnych: {powod}": "Cannot read restaurant versions: {powod}",
  "ten sam skład — różnica jest w technice": "same ingredients — the difference is in the technique",
  "Brak internetu — AI nie odpowie.": "No connection — the AI will not answer.",
  "Nie udało się — AI dwa razy oddało przepis z rozjazdem: {blad}": "That did not work — the AI twice returned a recipe that does not add up: {blad}",
  "Wersja restauracyjna gotowa.": "Restaurant version ready.",
  "Nie udało się ({etap}): {powod}": "That did not work ({etap}): {powod}",
  "Zdjęcia": "Photos",
  " · na {ile} os.": " · serves {ile}",
  "Przetwarzam zdjęcie {ktore} z {ile}…": "Processing photo {ktore} of {ile}…",
  "Wybrano {ile} — dotknij, żeby zmienić": "{ile} chosen — tap to change",
  "Nie udało się odczytać żadnego zdjęcia — spróbuj innych": "Could not read any of the photos — try different ones",
  "Wysyłam zdjęcia": "Sending photos",
  "AI odczytuje obraz": "AI is reading the image",
  "Zapisuje przepis": "Writing the recipe",
  "Sprawdzam składniki": "Checking ingredients",
  "Pytam AI": "Asking the AI",
  "Powstaje przepis": "Recipe on its way",
  "AI nie zdążyło przeczytać tych zdjęć w wyznaczonym czasie. Spróbuj z mniejszą liczbą — najlepiej jednym lub dwoma.": "The AI did not read these photos in time. Try fewer — one or two is best.",
  "AI nie zdążyło odpowiedzieć w wyznaczonym czasie. Spróbuj jeszcze raz.": "The AI did not answer in time. Try again.",
  "Coś poszło nie tak po stronie AI.": "Something went wrong on the AI side.",
  "{razem} s · AI {ai} s · stół {baza} s · {model}": "{razem} s · AI {ai} s · table {baza} s · {model}",
  "Pięćdziesiąt własnych dań. To już nie apka, to Wasza książka kucharska.": "Fifty dishes of your own. This is not an app any more, it is your cookbook.",
  "1 danie trafiło do Waszych dań.": "1 dish added to your dishes.",
  "{ile} dania trafiły do Waszych dań.": "{ile} dishes added to your dishes.",
  "Podaj nazwę dania.": "Enter the dish name.",
  "Wybierz przynajmniej jeden typ posiłku spośród: {typy}.": "Choose at least one meal type from: {typy}.",
  "Porcje muszą być liczbą całkowitą od 1 do 12.": "Servings must be a whole number from 1 to 12.",
  "Dodaj przynajmniej jeden składnik.": "Add at least one ingredient.",
  "Jeden ze składników nie ma wybranego produktu.": "One of the ingredients has no product chosen.",
  "„{produkt}” nie jest w słowniku produktów — wybierz z podpowiedzi.": "“{produkt}” is not in the product list — pick from the suggestions.",
  "Podaj poprawną gramaturę dla „{produkt}”.": "Enter a valid amount in grams for “{produkt}”.",
  "Dodaj Forkast do ekranu": "Add Forkast to your home screen",
  "Dotknij ikony udostępniania na dole, a potem „Dodaj do ekranu początkowego”. Forkast będzie wtedy wyglądał jak zwykła aplikacja — bez paska adresu.": "Tap the share icon at the bottom, then “Add to Home Screen”. Forkast will then look like a normal app — no address bar.",
  "Otwórz w Safari": "Open in Safari",
  "Żeby dodać Forkast do ekranu, otwórz go w Safari — inne przeglądarki na iPhonie tego nie potrafią.": "To add Forkast to your home screen, open it in Safari — other browsers on iPhone cannot do it.",
  "Będzie wyglądał jak zwykła aplikacja i otworzy się jednym dotknięciem.": "It will look like a normal app and open with one tap.",
  "Po co zaznaczać dania": "Why pick dishes",
  "Wszystko w tej aplikacji buduje się z dań, które tu polubicie. Jadłospis losuje tylko z nich, lista zakupów liczy tylko z nich. Nic nie pojawi się samo.": "Everything in this app is built from the dishes you like here. The meal plan draws only from them, the shopping list counts only from them. Nothing shows up on its own.",
  "Im więcej polubicie, tym mniej musicie potem robić. Przy dziesięciu daniach tygodniowy plan wraca do tych samych potraw co drugi dzień i trzeba go poprawiać ręcznie. Przy dwudziestu pięciu „Ułóż automatycznie” wystarcza — klikacie raz i macie miesiąc bez powtórki.": "The more you like, the less you have to do later. With ten dishes a plan comes back to the same food every other day and needs fixing by hand. With twenty-five, “Fill it in for us” is enough — one tap and a month without repeats.",
  "Nie pasuje Wam nic z tej listy? To też jest w porządku. Możecie zbudować własną od zera — zakładka Dodaj przyjmuje zdjęcie przepisu z książki albo samą nazwę dania. Aplikacja będzie wtedy losować wyłącznie z Waszych.": "Nothing on this list fits? That is fine too. You can build your own from scratch — the Add tab takes a photo of a recipe from a book or just the name of a dish. The app will then draw only from yours.",
  "Jak działa jadłospis": "How the meal plan works",
  "„Ułóż automatycznie” wypełnia cały okres daniami, które polubiliście, pilnując przy tym, żeby to samo nie wracało zbyt często. Każdy posiłek możecie potem podmienić ręcznie.": "“Fill it in for us” fills the whole period with dishes you liked, making sure the same thing does not come back too often. You can swap any meal by hand afterwards.",
  "Dotknięcie dania pokazuje przepis z gramaturą przeliczoną na tylu ludzi, ilu realnie je ten posiłek — nie na liczbę z książki kucharskiej.": "Tapping a dish shows the recipe with amounts scaled to the number of people who actually eat that meal — not the number from the cookbook.",
  "Są też trzy pozycje, których nie ma w żadnym przepisie, a są w życiu: „na mieście”, „co się nawinie” i „coś z paczki”. Żadna nie wchodzi do listy zakupów.": "There are also three options that no recipe has but real life does: “eating out”, “whatever's around” and “something ready-made”. None of them goes on the shopping list.",
  "Skąd bierze się ta lista": "Where this list comes from",
  "Lista liczy się sama z jadłospisu: sumuje składniki wszystkich dań w okresie, przelicza je na tylu ludzi, ilu siada do stołu, i grupuje po działach sklepu.": "The list counts itself from the meal plan: it adds up the ingredients of every dish in the period, scales them to the people at the table and groups them by shop aisle.",
  "Działa bez internetu. Możecie odhaczać w markecie, gdzie nie ma zasięgu — a to, co odhaczycie, zobaczy druga osoba przy tym samym stole.": "It works offline. You can tick things off in a shop with no signal — and the other person at the same table will see what you ticked.",
  "Spiżarnia odejmuje od listy to, co już macie w domu. Mąkę kupuje się w kilogramie, a na naleśniki idzie 250 g — bez spiżarni lista kazałaby kupować kilogram co tydzień.": "The pantry takes off the list what you already have at home. Flour comes in a kilo bag and pancakes need 250 g — without the pantry the list would tell you to buy a kilo every time.",
  "Trzy sposoby na własne dania": "Three ways to add your own dishes",
  "Zdjęcie: strona z książki kucharskiej, kartka z zeszytu babci, zrzut ekranu z Instagrama. Możecie też sfotografować sam talerz z jedzeniem — AI rozpozna, co na nim jest, i napisze przepis od zera.": "Photo: a cookbook page, a card from grandma's notebook, an Instagram screenshot. You can also photograph just the plate — the AI will recognise what is on it and write a recipe from scratch.",
  "Przepis z internetu: otwórzcie stronę w przeglądarce i zróbcie zrzut ekranu — wtedy AI czyta to, co naprawdę tam napisano, zamiast zgadywać z adresu.": "A recipe from the web: open the page in your browser and take a screenshot — then the AI reads what is actually written there instead of guessing from the address.",
  "Nazwa: wpisujecie „gołąbki” i tyle. Przepis powstaje z niczego. Zanim cokolwiek się zapisze, zobaczycie, co wyszło, i decydujecie sami.": "Name: type “lasagne” and that is it. The recipe is written from nothing. Before anything is saved you see what came out, and you decide.",
  "Skąd tu się biorą przepisy": "Where these recipes come from",
  "To wszystko, co polubiliście w zakładce Dania — z krokami i gramaturą.": "Everything you liked in the Dishes tab — with steps and amounts.",
  "Dania dodane ręcznie mogą nie mieć kroków, bo nikt ich nie wpisał. Można je uzupełnić przez AI w dowolnym momencie.": "Dishes added by hand may have no steps, because nobody typed them in. The AI can fill them in at any time.",
  "Wpisujecie, ile czego macie w domu. Lista zakupów odejmuje to od potrzeb, a produkty, których macie dość, dostają znaczek „mamy” i nie liczą się do tego, co trzeba kupić.": "You enter how much of what you have at home. The shopping list takes it off what you need, and products you have enough of get a “got it” mark and do not count towards what to buy.",
  "Wpiszcie tylko to, czego macie więcej niż na jeden raz — mąkę, ryż, olej, makaron. Nie ma sensu prowadzić tu spisu wszystkiego.": "Only enter what you have more than one use of — flour, rice, oil, pasta. There is no point keeping an inventory of everything.",
  "Po ugotowaniu okresu jeden przycisk odlicza zużycie. Nie robimy tego automatycznie, bo aplikacja nie wie, czy naprawdę ugotowaliście to, co zaplanowane.": "After you have cooked through a period, one button takes off what was used. We do not do it automatically, because the app does not know whether you really cooked what was planned.",
  "{data}, {posilek}: danie zniknęło z bazy — nie wliczam go do zakupów.": "{data}, {posilek}: the dish is gone from the database — not counting it in the shopping.",
  "{data}, {posilek}: nikt tego nie je, więc nie kupujemy składników.": "{data}, {posilek}: nobody eats this, so no ingredients to buy.",
  "„{danie}”: nie wiadomo, na ile osób jest ta gramatura — pomijam.": "“{danie}”: unclear how many people these amounts are for — skipping.",
  "{danie} (restauracyjna)": "{danie} (restaurant)",
  "{data}, {posilek}: „{danie}” zaplanowane w wersji restauracyjnej, ale tej wersji nie ma — liczę z podstawowej.": "{data}, {posilek}: “{danie}” is planned as the restaurant version, but that version does not exist — counting the basic one.",
  "Najpierw usiądź do stołu": "Take a seat at a table first",
  "Ta przeglądarka nie wie jeszcze, do którego stołu należysz. Załóż nowy albo wpisz kod, który ktoś Ci wysłał.": "This browser does not know yet which table you belong to. Set up a new one or enter the code someone sent you.",
  "Przejdź do stołu": "Go to the table",
  "posiłek": "meal",
  "Ekran świeci": "Screen stays on",
  "Ekran gaśnie": "Screen dims",
  "Ekran nie gaśnie, dopóki tu jesteś. Dotknij, żeby wyłączyć.": "The screen stays on while you are here. Tap to turn it off.",
  "Ekran gaśnie normalnie. Dotknij, żeby świecił.": "The screen dims as usual. Tap to keep it on.",
};

/**
 * @param {string} napis  polski napis, dokładnie taki jak w kodzie
 * @param {string} jezyk  "pl" albo "en"
 * @param {object} [wstawki]  wartości dla `{nazwa}` w napisie
 */
export function tlumacz(napis, jezyk, wstawki) {
  const gotowe = (!jezyk || jezyk === "pl") ? napis : (SLOWNIK[napis] ?? napis);
  return wstawki ? wstaw(gotowe, wstawki) : gotowe;
}

/* WSTAWKI — `t("Przejrzano {ile} z {z} dań", { ile, z })`.

   Po co, skoro v88 cięło takie zdania na kawałki tłumaczone osobno: kawałki
   nie zmieniają szyku. „kuchnia polska” to po angielsku „Polish cuisine”,
   „Usuń Ankę ze stołu” to „Remove Anka from the table” — liczba albo imię
   stoi w innym miejscu zdania niż po polsku i żadne sklejanie tego nie da.
   Wstawka stoi tam, gdzie ją postawi tłumaczenie.

   Klucz dalej jest polskim zdaniem, tylko z nazwaną dziurą — Miłosz czyta
   w kodzie, co będzie na ekranie. Wstawka bez wartości zostaje widoczna
   jako `{nazwa}`, żeby błąd było widać na ekranie, a nie zgadywać z pustki. */
function wstaw(tekst, wstawki) {
  return tekst.replace(/\{(\w+)\}/g, (cale, nazwa) =>
    wstawki[nazwa] === undefined || wstawki[nazwa] === null ? cale : String(wstawki[nazwa]));
}

/* ZNACZNIK `napis("…")` — nic nie robi, zwraca to, co dostał. Stoi w modułach
   przy danych, które trafią na ekran DOPIERO PÓŹNIEJ, przez t(zmienna): etykiety
   sprzętu, typy posiłków, akapity pomocy. Bez niego test widzi w słowniku pozycję,
   której „nikt nie woła”, a w module napis, o którym nie wie, że jest tekstem.
   Z nim jedno i drugie jest jawne — to ten sam pomysł co `N_()` w gettext. */
export const napis = tekst => tekst;

/** Polski z wypełnionymi wstawkami — domyślny tłumacz dla modułów wołanych bez ekranu
    (testy, logika). Ekran podaje zamiast tego swoje `t`, które zna język stołu. */
export const PO_POLSKU = (napis, wstawki) => tlumacz(napis, "pl", wstawki);

/* Język dla modułów, które nie mają dostępu do stanu Alpine. Ustawia go
   powłoka przy starcie ekranu i przy każdej zmianie — moduły same go nie
   czytają z bazy, bo wtedy każdy z nich musiałby znać stół. */
let jezykModulow = "pl";

export function ustawJezykModulow(jezyk) {
  jezykModulow = jezyk || "pl";
}

export function tb(napis, wstawki) {
  return tlumacz(napis, jezykModulow, wstawki);
}

/** Dla testu: napisy używane w kodzie, których nie ma w słowniku. */
export function brakujace(napisy) {
  return [...new Set(napisy)].filter(n => !(n in SLOWNIK));
}
